# Generated by Django 2.2.10 on 2020-02-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empcms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
